### ISSUE TITLE
 Error while setting up optispark platform for climate 

### ISSUE THREAD

**Issue by chappers00** [Big-Tree/HomeAssistant-OptiSpark#27]
### System Health details

 Core 2024.1.3
Supervisor 2023.12.0
Operating System 11.4
Frontend 20240104.0

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/Big-Tree/HomeAssistant-OptiSpark/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Logger: homeassistant.components.climate
Source: helpers/entity_platform.py:368
Integration: Climate (documentation, issues)
First occurred: 8:11:00 AM (1 occurrences)
Last logged: 8:11:00 AM

Error while setting up optispark platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 368, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 752, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1282, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 945, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1066, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1005, in __async_calculate_state
    attr.update(self.state_attributes or {})
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 355, in state_attributes
    hass, self.current_temperature, temperature_unit, precision
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/optispark/climate.py", line 157, in current_temperature
    return self.coordinator.house_temperature
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/optispark/coordinator.py", line 216, in house_temperature
    entity = get_entity(self.hass, self._climate_entity_id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/optispark/__init__.py", line 90, in get_entity
    raise OptisparkGetEntityError(f'({len(entities_found)}) entities found instead of 1')
custom_components.optispark.OptisparkGetEntityError: (0) entities found instead of 1

### Reproduction steps

1. Install Optispark
2. Restart HA
3. Connect it to LG Heat pump
...

### Debug logs

```text
tbc
```

**Comment by chappers00** [comment]
![image](https://github.com/Big-Tree/HomeAssistant-OptiSpark/assets/4682866/b6a07708-a8e5-44e1-bcf9-db0d546e8de0)

**Comment by chappers00** [comment]
![image](https://github.com/Big-Tree/HomeAssistant-OptiSpark/assets/4682866/e801e3c2-7d9b-4827-ac1c-f831f06e46ff)

**Comment by Big-Tree** [comment]
Thanks.  This usually occurs when the integration has just been configured and it's waiting on the lambda function to return data.  I've had a look and there were no issues with Lambda, so I'd expect it to resolve itself after a minute.

Did it resolve itself?  What version of the integration are you running?  I've just tested 1.5 (released last 3 days ago) and it's working for me.

**Comment by Big-Tree** [comment]
From the error log it's saying that it cannot access your heat pump entity.  This occurs when home assistant has just been rebooted and the OptiSpark integration loads before the heat pump.

I'd expect the error to resolve itself after the heat pump integration loads and becomes available.

If it doesn't resolve I find this surprising since you have gotten it working before.  Perhaps there is another error in the logs since the one you shared usually appears after a reboot?

**Comment by chappers00** [comment]
Fixed
